import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AuthProvider } from './context/AuthContext'
import { CartProvider } from './context/CartContext'
import { PricingProvider } from './context/PricingContext'
import { ThemeProvider } from './context/ThemeContext'
import { LogoutTransitionProvider } from './context/LogoutTransitionContext'
import './styles.css'
import './management-theme.css'
import './cashier-polish.css'
import './pricing.css'
import './purchase-orders.css'
import './cashier-refined.css'
import './cashier-surfaces.css'
import './admin-reference.css'
import './admin-dark-palette.css'
import './staff-reference.css'
import './management-neutral-overlays.css'
createRoot(document.getElementById('root')).render(<StrictMode><BrowserRouter><ThemeProvider><PricingProvider><AuthProvider><CartProvider><LogoutTransitionProvider><App /></LogoutTransitionProvider></CartProvider></AuthProvider></PricingProvider></ThemeProvider></BrowserRouter></StrictMode>)

